name: .NET

on:
  push:
    branches: [ CL/BN_UpQD4xn1_test-coverage-tool ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install tools
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Testing with Coverlet tool collection
      run: dotnet test --no-build --collect:"XPlat Code Coverage"

    - name: Reportgenerator tool create badges
      run: reportgenerator -reports:"/home/runner/work/art-store-back-end/art-store-back-end/Art Store Backend Tests/TestResults/*/coverage.cobertura.xml" -targetdir:"TestResults/badges" -reporttypes:badges
