name: .NET

on:
  push:
    branches: [ CL/BN_UpQD4xn1_test-coverage-tool ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install tools
      run: dotnet tool install dotnet-reportgenerator-globaltool
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Coverlet tool collection
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Reportgenerator tool create badges
      run: reportgenerator -reports:TestResults\*\coverage.cobertura.xml -targetdir:reports/badges -reporttypes:badges
